---
- name: Create directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
  - { path: '{{ nginx_proxy_dir }}', state: 'directory' }
  
- name: Create proxy network for nginx
  docker_network:
    name: {{ docker_network_name }}
