---
- name: Restart database
  command: "docker exec -d {{ db_container }} /bin/bash -c 'service mysqld restart'"
    
- name: Restart app
  command: "docker exec -d {{ app_container }} /bin/bash -c 'service apache2 reload'"
