---
- name: Restart database
  command: "docker exec -d {{ db_container }} /bin/bash -c 'systemctl reload mysqld'"
    
- name: Restart app
  command: "docker exec -d {{ app_container }} /bin/bash -c 'systemctl reload httpd'"
