---
- hosts: NetrisAppointments
  remote_user: netris
  become: yes
  gather_facts: no
  vars_files:
  - roles/mysql/vars/pw.yml
  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  tasks:
  - name: Install MySQL-python
    yum:
      name: MySQL-python
      state: present
      update_cache: yes
  - name: backup databases
    mysql_db:
      state: dump
      name: "{{ item }}"
      login_user: root
      login_password: {{ na_root_pw }}
      target: /home/netris/backup/netriscal_{{ item }}_{{ date }}.sql
    with_items:
    - netriscal
    - emailqueue
