---
- hosts: NetrisAppointments
  remote_user: netris
  become: yes
  gather_facts: no
- name: backup databases
  mysql_db:
    state=dump
    name={{ item }}
    target=/home/netris/backup/netriscal_{{ item }}_{{ansible_date_time.date }}.sql
  with_items:
  - netriscal
  - emailqueue
