---
- hosts: NetrisAppointments
  remote_user: netris
  become: yes
  gather_facts: no
  vars:
    app_name: NetrisAppointments
  vars_files:
  - roles/lemp/vars/main.yml
  roles:
  - common
  - lemp
  - ssl
  - NetrisAppointments
