---
# Playbook to provision Netris Appointments servers with LEMP stack

- hosts: NetrisAppointments
  remote_user: netris
  become: yes
  gather_facts: no
  tasks:
  - name: install nginx
    yum: name=nginx state=installed
