---
- hosts: WebServers
  remote_user: netris
  become: yes
  gather_facts: no
  vars_files:
  - roles/lemp/vars/main.yml
  vars:
    app_name: wordpress
  roles:
  - common
  - docker
  - docker-nginx
  - docker-wordpress
