---
- hosts: webservers
  remote_user: netris
  become: yes
  gather_facts: no
  vars_files:
  - roles/lemp/vars/main.yml
  vars:
    app_name: wordpress
    restore_to: 20180608
  roles:
  - common
  - wp-restore
