---
- name: Create directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
  - { path: '{{ instance_root }}', state: 'directory' }
  
- name: Copy template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { src: 'docker-compose.yml.j2', dest: '{{ instance_root }}/docker-compose.yml' }
    
- name: Run Docker containers with compose
  command: "chdir={{ instance_root }} docker-compose up -d"
  
- name: Create config dir
  command: "docker exec -d {{ app_container }} /bin/bash -c 'mkdir -p {{ app_config_dir }}'"  

- name: Move config file to new dir
  command: "docker exec -d {{ app_container }} /bin/bash -c 'cp -n {{ app_root }}/include/config.php {{ app_config_dir }}/'"
  
- name: Create symlink to config file
  command: "docker exec -d {{ app_container }} /bin/bash -c 'ln -s {{ app_config_dir }}/config.php {{ app_root }}/config.php'"
  
- name: Change permissions on symlink
  command: "docker exec -d {{ app_container }} /bin/bash -c 'chown -h www-data:www-data {{ app_root }}/config.php'"
