---
- name: Check if install files exist
  stat:
    path: "/home/netris/{{ item }}.sql.xz"
  register: instfile
  with_items:
  - nadb
  - eqdb
  
- name: Check if databases exist
  command: "mysql -u root -p{{ na_root_pw }} -e 'SHOW DATABASES;' | grep {{ item }}"
  register: database
  failed_when: database.rc == 2
  with_items:
  - "{{ na_database }}"
  - "{{ eq_database }}"
  
- name: Extract database files
  command: "xz -dkf /home/netris/{{ item }}.sql.xz"
  when:
  - database.rc == 1
  - instfile.stat.exists == True
  with_items:
  - "{{ na_database }}"
  - "{{ eq_database }}"
    
- name: Install databases
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.src }}"
    state: "{{ item.state }}"
  when:
  - database.rc == 1
  - instfile.stat.exists == True
  with_items:
  - { name: '{{ na_database }}', src: '/home/netris/nadb.sql', state: 'import' }
  - { name: '{{ eq_database }}', src: '/home/netris/eqdb.sql', state: 'import' }
  
- name: Cleanup leftover files
  command: "rm -f /home/netris/{{ item }}.sql"
  when:
  - database.rc == 1
  - instfile.stat.exists == True
  with_items:
  - nadb
  - eqdb
