---
- name: Check if install files exist
  stat:
    path: "/home/netris/nadb.sql.xz"
  register: instfile1
  stat:
    path: "/home/netris/eqdb.sql.xz"
  register: instfile2
  
- name: Check if databases exist
  command: "mysql -u root -p{{ na_root_pw }} -e 'SHOW DATABASES;' | grep {{ na_database }}"
  register: database1
  failed_when: database.rc == 2
  command: "mysql -u root -p{{ na_root_pw }} -e 'SHOW DATABASES;' | grep {{ eq_database }}"
  register: database2
  failed_when: database.rc == 2
  
- name: Extract database files
  command: "xz -dkf /home/netris/{{ item }}.sql.xz"
  when:
  - instfile1.stat.exists == True
  - instfile2.stat.exists == True
  - database1.rc == 1
  - database2.rc == 1
  with_items:
  - nadb
  - eqdb
    
- name: Install databases
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.src }}"
    state: "{{ item.state }}"
  when:
  - instfile1.stat.exists == True
  - instfile2.stat.exists == True
  - database1.rc == 1
  - database2.rc == 1
  with_items:
  - { name: '{{ na_database }}', src: '/home/netris/nadb.sql', state: 'import' }
  - { name: '{{ eq_database }}', src: '/home/netris/eqdb.sql', state: 'import' }
  
- name: Cleanup leftover files
  command: "rm -f /home/netris/{{ item }}.sql"
  when:
  - instfile1.stat.exists == True
  - instfile2.stat.exists == True
  - database1.rc == 1
  - database2.rc == 1
  with_items:
  - nadb
  - eqdb
