---
- name: Create directories
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
  with_items:
  - { path: '{{ etc_dir }}', state: 'directory' }
  - { path: '{{ etc_dir }}/emailqueue', state: 'directory' }
  - { path: '{{ www_dir }}', state: 'directory', owner: '{{ http_user }}', group: '{{ http_user }}' }
  - { path: '{{ www_dir }}/emailqueue', state: 'directory', owner: '{{ http_user }}', group: '{{ http_user }}' }
  - { path: '{{ www_dir }}/uploads', state: 'directory', owner: '{{ http_user }}', group: '{{ http_user }}' }
  
- name: Remove framework index.html
  file:
    src: "{{ item.src | default('omit') }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { dest: '{{ www_dir }}/index.html', state: 'absent' }

- name: Copy config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { src: 'na_config.php.j2', dest: '{{ etc_dir }}/na_config.php', owner: '{{ http_user }}', group: '{{ http_user }}' }
  - { src: 'eq_config.php.j2', dest: '{{ etc_dir }}/emailqueue/eq_config.php' }
  - { src: 'delivery.php.j2', dest: '{{ etc_dir }}/emailqueue/delivery.php' }
  - { src: 'purge.php.j2', dest: '{{ etc_dir }}/emailqueue/purge.php' }
  - { src: 'na_index.php.j2', dest: '{{ www_dir }}/index.php', owner: '{{ http_user }}', group: '{{ http_user }}' }
  - { src: 'eq_index.php.j2', dest: '{{ www_dir }}/emailqueue/index.php', owner: '{{ http_user }}', group: '{{ http_user }}' }
  - { src: 'emailqueue.php.j2', dest: '{{ www_dir }}/emailqueue/emailqueue.php', owner: '{{ http_user }}', group: '{{ http_user }}' }

- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state | default('link') }}"
    owner: "{{ item.owner | default('nginx') }}"
    group: "{{ item.group | default('nginx') }}"
  with_items:
  - { src: '/usr/share/{{ app_name }}/src/application', dest: '{{ www_dir }}/application' }
  - { src: '/usr/share/{{ app_name }}/src/assets', dest: '{{ www_dir }}/assets' }
  - { src: '/usr/share/{{ app_name }}/src/engine', dest: '{{ www_dir }}/engine' }
  - { src: '/usr/share/{{ app_name }}/src/storage', dest: '{{ www_dir }}/storage' }
  - { src: '/usr/share/{{ app_name }}/src/system', dest: '{{ www_dir }}/system' }
  - { src: '/usr/share/{{ app_name }}/src/vendor', dest: '{{ www_dir }}/vendor' }
  - { src: '/usr/share/{{ app_name }}/src/autoload.php', dest: '{{ www_dir }}/autoload.php' }
  - { src: '/usr/share/{{ app_name }}/src/functions.php', dest: '{{ www_dir }}/functions.php' }
  - { src: '/usr/share/{{ app_name }}/src/emailqueue/gfx', dest: '{{ www_dir }}/emailqueue/gfx' }
  - { src: '/usr/share/{{ app_name }}/src/emailqueue/favicon.ico', dest: '{{ www_dir }}/emailqueue/favicon.ico' }
  - { src: '/etc/{{ app_name }}/src/easyappointments-master', dest: '{{ etc_dir }}/easyappointments-master', owner: 'root', group: 'root' }
  - { src: '/etc/{{ app_name }}/src/flowroute-messaging-php', dest: '{{ etc_dir }}/flowroute-messaging-php', owner: 'root', group: 'root' }
  - { src: '/etc/{{ app_name }}/src/emailqueue/classes', dest: '{{ etc_dir }}/emailqueue/classes', owner: 'root', group: 'root' }
  - { src: '/etc/{{ app_name }}/src/emailqueue/lib', dest: '{{ etc_dir }}/emailqueue/lib', owner: 'root', group: 'root' }
  - { src: '/etc/{{ app_name }}/src/emailqueue/common.inc.php', dest: '{{ etc_dir }}/emailqueue/common.inc.php', owner: 'root', group: 'root' }
  - { src: '/etc/{{ app_name }}/src/emailqueue/scripts/emailqueue_inject.class.php', dest: '{{ etc_dir }}/emailqueue/emailqueue_inject.class.php', owner: 'root', group: 'root' }
  
- name: Create cron jobs for emailqueue
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.minute | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    state: present
  with_items:
  - { name: '{{ inventory_hostname }} Delivery Script', job: 'php -q {{ etc_dir }}/emailqueue/delivery.php' }
  - { name: '{{ inventory_hostname }} Purge Script', job: 'php -q {{ etc_dir }}/emailqueue/purge.php', minute: '0', hour: '6' }
