---
instance_root: "/usr/share/{{ app_name }}/{{ inventory_hostname }}"
html_root: /var/www/html
db_container: "{{ inventory_hostname.split('.')[0] }}_{{ inventory_hostname.split('.')[1] }}_{{ inventory_hostname.split('.')[2] }}_{{ app_name }}_db"
wp_container: "{{ inventory_hostname.split('.')[0] }}_{{ inventory_hostname.split('.')[1] }}_{{ inventory_hostname.split('.')[2] }}_{{ app_name }}"
letsencrypt_email: admin@netris.us
wp_config_dir: "/etc/{{ app_name }}"
