- name: backup databases
  mysql_db:
    state: dump
    login_user: "{{ item.user | default('root') }}"
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.target }}"/home/netris/backup/na_{{ item }}_{{ date }}.sql.xz
  with_items:
  - { name: '{{ na_database }}', target: '/home/netris/backup/{{ na_database }}_{{ date }}.sql.xz' }
  - { name: '{{ eq_database }}', target: '/home/netris/backup/{{ eq_database }}_{{ date }}.sql.xz' }

- name: Backup directories
