---
- name: Backup databases
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { name: '{{ na_database }}', dest: '/home/netris/backup/{{ na_database }}_{{ date }}.sql.xz', state: 'dump' }
  - { name: '{{ eq_database }}', dest: '/home/netris/backup/{{ eq_database }}_{{ date }}.sql.xz', state: 'dump' }

- name: Backup directories
