- name: backup databases
  mysql_db:
    state: dump
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item }}"
    target: /home/netris/backup/netriscal_{{ item }}_{{ date }}.sql.xz
  with_items:
  - netriscal
  - emailqueue
