---
- name: Backup {{ app_name }} databases
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { name: '{{ na_database }}', dest: '/home/netris/backup/{{ na_database }}_{{ date }}.sql.xz', state: 'dump' }
  - { name: '{{ eq_database }}', dest: '/home/netris/backup/{{ eq_database }}_{{ date }}.sql.xz', state: 'dump' }

- name: Change permissions on database backups
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('netris') }}"
    group: "{{ item.group | default('netris') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { path: '/home/netris/backup/{{ na_database }}_{{ date }}.sql.xz' }
  - { path: '/home/netris/backup/{{ eq_database }}_{{ date }}.sql.xz' }
  
- name: Backup {{ app_name }} codebase
  archive:
    path: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('netris') }}"
    group: "{{ item.group | default('netris') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { dest: '/home/netris/backup/nawww_{{ date }}.tar.xz', src: '/etc/{{ app_name }}/src' }
  - { dest: '/home/netris/backup/naetc_{{ date }}.tar.xz', src: '/usr/share/{{ app_name }}/src' }
  - { dest: '/home/netris/backup/{{ inventory_hostname }}_nawww_{{ date }}.tar.xz', src: '/etc/{{ app_name }}/{{ inventory_hostname }}' }
  - { dest: '/home/netris/backup/{{ inventory_hostname }}_naetc_{{ date }}.tar.xz', src: '/usr/share/{{ app_name }}/{{ inventory_hostname }}' }
