---
- name: Backup {{ app_name }} databases
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { name: '{{ na_database }}', dest: '/home/netris/backup/{{ na_database }}_{{ date }}.sql.xz', state: 'dump' }
  - { name: '{{ eq_database }}', dest: '/home/netris/backup/{{ eq_database }}_{{ date }}.sql.xz', state: 'dump' }

- name: Backup {{ app_name }} codebase
  archive:
    path: "{{ item.src }}"
    dest: "/home/netris/backup/{{ item.name }}.tar.xz"
  with_items:
  - { name: 'naetc', src: '/etc/{{ app_name }}/src' }
  - { name: 'nawww', src: '/usr/share/{{ app_name }}/src' }
