---
- name: backup databases
  mysql_db:
    state=dump
    name={{ item }}
    target=/usr/netris/backup/netriscal_{{ item }}_{{ansible_date_time.date }}.sql
  with_items:
  - netriscal
  - emailqueue
