---
- name: Install Certbot
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - certbot-nginx

- name: Check if cert already exists
  stat:
    path: "/etc/letsencrypt/live/{{ inventory_hostname }}/cert.pem"
  register: cert
  
- name: Stop nginx
  service:
    name: nginx
    state: stopped
  when: cert.stat.exists == False
  
- name: Generate cert
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ inventory_hostname }}"
  args:
    creates: "{{ certbot_output_dir }}"
  when: cert.stat.exists == False
  notify:
  - Create Cron Job

- name: Start Nginx
  service: 
    name: nginx
    state: started

- name: Create cron job to auto renew certificate
  cron: 
    name: Renew LetsEncrypt Cert
    special_time: daily
    job: "{{ certbot_script }} renew --pre-hook \"systemctl stop nginx\" --post-hook \"systemctl start nginx\" --quiet"
    state: present
  when: certbot_auto_renew
