---
- name: Install Certbot
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - certbot-nginx
  - 
  notify:
  - Stop Nginx

- name: Generate cert
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ inventory_hostname }}"
  args:
    creates: "{{ certbot_output_dir }}"

- name: Start Nginx
  service: 
    name: nginx
    state: started

- name: Create cron job to auto renew certificate
  cron: 
    name: Renew LetsEncrypt Cert
    special_time: daily
    job: "{{ certbot_script }} renew --standalone --no-self-upgrade --pre-hook \"systemctl stop nginx\" --post-hook \"systemctl start nginx\" --quiet"
    state: present
