---
- name: Install Common Packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
  - epel-release
  - MySQL-python
  - python-simplejson
  - nano
  - openssh-server
  - vsftpd
  - fail2ban
  
- name: Disabled selinux
  selinux:
    state: disabled
    
- name: Copy Config Files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('644') }}"
  with_items:
  - { src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config', mode: '600' }
  - { src: 'vsftpd.conf.j2', dest: '/etc/vsftpd/vsftpd.conf', mode: '600' }
  notify:
  - Restart SSH
  
- name: Set Service parameters
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'fail2ban', enabled: 'yes', state: 'started' }
  - { name: 'sshd', enabled: 'yes', state: 'started' }
  - { name: 'vsftpd', enabled: 'no', state: 'stopped' }
