---
- name: Install LEMP Stack
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - nginx
  - mariadb
  - mariadb-server
  - php
  - php-fpm
  - php-cli
  - php-mysql
  notify:
  - RestartNginx
  - RestartMariadb
  - RestartPHP-FPM
