---
- name: Install Nginx
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - nginx
- name: Copy Nginx config files
  notify:
  - Restart Nginx
- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - mariadb
  - mariadb-server
- name: Copy MySQL config files
  notify:
  - Restart MySQL
- name: Install PHP
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - php
  - php-fpm
  - php-cli
  - php-mysql
- name: Copy PHP config files
  notify:
  - Restart PHP-FPM
