---
- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - mariadb
  - mariadb-server
  
- name: Set the root password 
  mysql_user: 
    login_user: root
    login_password: "{{ sql_root_pw }}"
    user: root
    password: "{{ sql_root_pw }}"

- name: Secure the root user
  mysql_user: 
    login_user: root
    login_password: "{{ sql_root_pw }}"
    user: root
    password: "{{ sql_root_pw }}"
    host: "{{ item }}"
  with_items:
  - ::1
  - 127.0.0.1
  - localhost
  - "{{ ansible_fqdn }}"

- name: Deletes anonymous server user
  mysql_user:
    login_user: root
    login_password: "{{ sql_root_password }}"
    user: ""
    host_all: yes
    state: absent

- name: Removes the test database
  mysql_db:
    login_user: root
    login_password: "{{ sql_root_pw }}"
    db: test
    state: absent
  
- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
  
- name: Copy MySQL config files
  notify:
  - Restart MySQL

- name: Enable MySQL service
  service:
    name: mariadb
    enabled: yes
