---
- name: Install Nginx / remove Apache
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'httpd', state: 'absent' }
  - { name: 'nginx', state: 'present' }
  
- name: Create instance directory
  file:
    path: "{{ instance_root }}"
    state: directory
    mode: 0755
    
- name: remove default files and create symlinks
  file:
    src: "{{ item.src | default('omit') }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { dest: '/etc/nginx/conf.d/default.conf', state: 'absent' }
  - { dest: '/usr/share/nginx/html/index.html', state: 'absent' }

- name: Copy Nginx config files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'virtualhost.conf.j2', dest: '/etc/nginx/conf.d/{{ inventory_hostname }}.conf' }
    - { src: 'index.php.j2', dest: '{{ instance_root }}/index.php', owner: '{{ http_user }}', group: '{{ http_user }}' }
  notify:
  - Restart Nginx
  
- name: Set Service parameters
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  with_items:
  - { name: 'nginx', enabled: 'yes', state: 'started' }
