---
instance_root: "/usr/share/{{ app_name }}/{{ inventory_hostname }}"
host_split: "{{ inventory_hostname.split('.')[0] }}_{{ inventory_hostname.split('.')[1] }}_{{ inventory_hostname.split('.')[2] }}"
app_container: "{{ host_split }}_{{ app_name }}"
db_container: "{{ app_container }}_db"
letsencrypt_email: admin@netris.us
app_config_dir: "/etc/{{ app_name }}"
html_root: "/var/www/html/{{ app_name }}"
db_user: cactiuser
