---
nginx_conns: 1024
http_port: 80
instance_root: "/usr/share/{{ app_name }}/{{ inventory_hostname }}"
host_split: "{{ inventory_hostname.split('.')[0] }}-{{ inventory_hostname.split('.')[1] }}-{{ inventory_hostname.split('.')[2] }}"
pool_name: "{{ host_split }}_{{ app_name }}"
fpm_sock: "/var/run/php-fpm/php-fpm-{{ pool_name }}.sock"
http_user: nginx
max_child: 5
start_serv: 2
min_spare_serv: 1
max_spare_serv: 5
php_daemonize: yes
