---
- name: Install Docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'apt-transport-https', state: 'latest' }
  - { name: 'ca-certificates', state: 'latest' }
  - { name: 'docker', state: 'present' }
  - { name: 'docker-compose', state: 'present' }
