---
- name: Install Prerequisites
  yum:
    name: "{{ item.name }}"
    state: latest
    update_cache: yes
  with_items:
  - 'apt-transport-https'
  - 'ca-certificates'

- name: Install Docker
  yum:
    name: "{{ item.name }}"
    state: present
    update_cache: yes
  with_items:
  - 'docker-{{ docker_edition }}-{{ docker-version }}'
  - 'docker-compose'
