---
- name: Install Prerequisites
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'apt-transport-https', state: 'latest' }
  - { name: 'ca-certificates', state: 'latest' }

- name: Install Docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'docker-{{ docker_edition }}={{ docker-version }}', state: 'present' }
  - { name: 'docker-compose', state: 'present' }
