---
- name: Install Prerequisites
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'apt-transport-https', state: 'latest' }
  - { name: 'ca-certificates', state: 'latest' }

- name: Install Docker
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  with_items:
  - { name: 'docker-{{ docker_edition }}={{ docker_version }}', state: 'present' }
  - { name: 'docker-compose', state: 'present' }
  
- name: Ensure Docker is started
  service:
    name: docker
    state: started
