---
- name: check if Docker is installed
  stat:
    path: /usr/bin/docker
  register: docker
  
- name: unarchive backup file
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - { src: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ restore_to }}.xz', dest: '/home/netris/backup/{{ inventory_hostname }}/' }
  - { src: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ restore_to }}', dest: '/home/netris/backup/{{ inventory_hostname }}/' }
   
- import_tasks: docker.yml
  when: docker.stat.exists == True
  
- import_tasks: bare_metal.yml
  when: docker.stat.exists == False
