- name: backup {{ app_name }} database
  mysql_db:
    login_user: root
    login_password: "{{ na_root_pw }}"
    name: "{{ item.name }}"
    target: "{{ item.dest }}"
    state: "{{ item.state }}"
  with_items:
  - { name: '{{ app_name }}', dest: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.sql.xz', state: 'dump' }

- name: Change permissions on database backups
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('netris') }}"
    group: "{{ item.group | default('netris') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { path: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.sql.xz' }
  
- name: Backup {{ app_name }} codebase
  archive:
    path: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('netris') }}"
    group: "{{ item.group | default('netris') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { dest: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.tar.xz', src: '/usr/share/nginx/html' }
