---
- name: backup {{ app_name }} database
  command: "docker exec -d {{ db_container }} /bin/bash -c 'mysqldump -u root -p{{ na_root_pw }} {{ app_name }} > /root/{{ app_name }}_{{ date }}.sql'"
  
- name: copy db backup to host
  command: "docker cp {{ db_container }}:/root/{{ app_name }}_{{ date }}.sql /home/netris/backup/{{ inventory_hostname }}/"
  
- name: remove backup file from docker
  command: "docker exec -d {{ db_container }} /bin/bash -c 'rm -f /root/{{ app_name }}_{{ date }}.sql'"
  
- name: backup {{ app_name }} codebase
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'tar -cvf /root/{{ app_name }}_{{ date }}.tar -C /var/www html'"
  
- name: copy codebase backup  to host
  command: "docker cp {{ wp_container }}:/root/{{ app_name }}_{{ date }}.tar /home/netris/backup/{{ inventory_hostname }}/"
  
- name: remove backup file from docker
  command: "docker exec -d {{ wp_container }} /bin/bash -c 'rm -f /root/{{ app_name }}_{{ date }}.tar'"  
  
- name: compress backed up files  
  archive:
    path: 
    - /home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.sql
    - /home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.tar
    dest: /home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.xz
    format: xz
    remove: yes
    
- name: Change permissions on backups
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner | default('netris') }}"
    group: "{{ item.group | default('netris') }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items:
  - { path: '/home/netris/backup/{{ inventory_hostname }}/{{ app_name }}_{{ date }}.xz' }
